### ISSUE TITLE
README.md comments on satisfy_general seems wrong

### ISSUE THREAD

**Issue by azdagron** [ecordell/pymacaroons#16]
The comments around satisfy_general say:
```python
# General caveats are verified by arbitrary functions
# that return false if the caveat is not met
# and true if it is met or not understood
```

The statement `and true if it is met or not understood` does not seem to match the implementation. The implementation is such that it should return False if not understood. As implemented, If any satisfy_general callback returns True the macaroon is valid.

Example code:
```python
from pymacaroons import Macaroon, Verifier

def foo(predicate):
    print("foo", predicate)
    return True

def bar(predicate):
    print("bar", predicate)
    return False

m = Macaroon(key='key', location='location', identifier='identifier')

m.add_first_party_caveat('key1 = value1')
m.add_first_party_caveat('key2 = value2')

v = Verifier()
v.satisfy_general(foo)
v.satisfy_general(bar)

try:
    print(v.verify(m, 'key'))
except Exception as e:
    print(e)
```

Even though bar returns False, the macaroon is "valid" since foo returns True, which is expected according to the implementation but goes against the comment.

The implementation currently matches libmacaroons python bindings as well.

So I think the comment just needs to be updated to say to return True if the predicate is both understood and met, otherwise false.

**Comment by ecordell** [comment]
Thanks @azdagron for taking the time to notice this problem and write up a detailed explanation! You're absolutely right - a caveat is considered "verified" if at least one caveat verifier returns `True`. I'll update the documentation to reflect this nuance.
