### ISSUE TITLE
Superfluous upper bound on libnacl?

### ISSUE THREAD

**Issue by cjwatson** [ecordell/pymacaroons#21]
pymacaroons declares `libnacl>=1.3.6,<1.4` in `install_requires`, but the functional tests seem to pass just fine with libnacl 1.4.5.  Is the upper bound here superfluous, or can it at least be bumped?  I don't see anything in the changes for libnacl 1.4.0 that would indicate a compatibility break.

**Comment by ecordell** [comment]
Happy to bump it if the tests are passing - I pin to a small range to limit possible incompatibilities. I'll get to it tonight or I'm happy to merge a PR before then if you're willing to issue one.
