### ISSUE TITLE
json deserialize raises an exception on missing vid or cl

### ISSUE THREAD

**Issue by rogpeppe** [ecordell/pymacaroons#25]
The vid and cl fields are optional in the JSON macaroon format, but
JsonSerializer.deserialize raises a missing key exception
if a caveat doesn't have them.

Probably the code should be:

    verification_key_id=(
                    standard_b64decode(c['vid']) if c.get('vid') else None
                ),

(using `c.get('vid')` rather than `c['vid']`)

**Comment by ecordell** [comment]
Fixed in #28
