### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by dimaqq** [ecordell/pymacaroons#47]
`README.md` starts with:

> This is a Python implementation of Macaroons. It is still under active development but is in a useable state - please report any bugs in the issue tracker.

At the same time, last commit was 10 months ago, so "active development" seems a bit off.

Assuming that the project has not been abandoned or put on the back burner, I imagine that "useable state" is not accurate either -- it kinds conveys "can be used for some purposes, but there are large known issues"

I propose that README is updated :)

**Comment by ecordell** [comment]
Good point!

The issues track where the project will go, but it’s stable and can be used
today. There are no known issues that aren’t already listed in github.
