### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by BigSamu** [ecordell/pymacaroons#56]
Hi,

Question, this library is still under development? Would like to use it, however I see a tag with a label "build:falling" in the documentation. Are there any important issues to be aware of?

![image](https://user-images.githubusercontent.com/28614451/144638467-bd6270c5-f89e-4c1e-b629-57350197bab1.png)

Thanks!

**Comment by ecordell** [comment]
There's not a lot of active development going on, but it is stable and useable.

For whatever reason, the badge is reporting the status of #54 instead of the last run on `master` - I'll take a look and see why that's happening.
