### ISSUE TITLE
Comparing two identical deserialized macaroons doesn't seem possible?

### ISSUE THREAD

**Issue by miketheman** [ecordell/pymacaroons#62]
Example:

```python
import pymacaroons

SERIALIZED_MACAROON = "MDAyMWxvY2F0aW9uIGh0dHBzOi8vZXhhbXBsZS5jb20KMDAxYmlkZW50aWZpZXIgdXNlcm5hbWUxMjMKMDAyZnNpZ25hdHVyZSB24dEoAhniYx228C6bPKNBsdHCEsIcDF9y5oQtG_Wl7wo"

deserialized1 = pymacaroons.Macaroon.deserialize(SERIALIZED_MACAROON)
deserialized2 = pymacaroons.Macaroon.deserialize(SERIALIZED_MACAROON)

assert deserialized1 == deserialized2
```
Returns `False`, and I think it should return `True`.

Does the Macaroon class need `__eq__` implemented, or is there some other way to compare Macaroons?

**Comment by ecordell** [comment]
I'm not opposed to implementing `__eq__`, but it's simple enough to check equality via their signatures:

```python
        assert deserialized1.signature == deserialized2.signature
```

**Comment by miketheman** [comment]
That's ... almost too simple. 🤦 

Thanks for the pointer! Happy to close this, or leave it open if you want to implement `__eq__` based on signature comparison, I guess?
